### ISSUE TITLE
Good-to-haves list

### ISSUE THREAD

**Issue by IkerAlus** [bee344/coretime-renewal-bot#1]
A list of improvements for the bot in the current version:

- [x]  Let the user input the relevant core to be renewed to `core_to_renew`.
- [x] If the user account does not have enough funds, output a warning / notification.
- [x] Include the option to query `broker.allowedRenewals` storage entry for the relevant core so that users can get an idea of the status of the relevant node
- [x] Add comments to important steps in the code.

**Comment by bee344** [comment]
Closed by #3
