### ISSUE TITLE
Comments on the flow design of the bot

### ISSUE THREAD

**Issue by IkerAlus** [bee344/coretime-renewal-bot#2]
In the current implementation the bot will not exit when:
- there are not enough funds ([here](https://github.com/bee344/coretime-renewal-bot/blob/42c4de66e8f359f697e6a6f9d8a8ebb888d93bb0/src/main.rs#L112) and [here](https://github.com/bee344/coretime-renewal-bot/blob/42c4de66e8f359f697e6a6f9d8a8ebb888d93bb0/src/main.rs#L140)) 
- the relevant core is not [renewable](https://github.com/bee344/coretime-renewal-bot/blob/42c4de66e8f359f697e6a6f9d8a8ebb888d93bb0/src/main.rs#L103)
- The tx is submitted successfully and [the core is renewed](https://github.com/bee344/coretime-renewal-bot/blob/42c4de66e8f359f697e6a6f9d8a8ebb888d93bb0/src/main.rs#L136)

and just keep looping these checks for every new block. 

Note that the [the originally proposed design](https://docs.google.com/document/d/1J1hhINw5t7nFNdN8wG-V56Pyt_VnXJiN0M_1f-EKUjc/edit#heading=h.4pzlbitk7s8u) would exit as soon as the core is not renewable or are not enough funds. I think this implementation is a better design than the original since it is better to not exit and just warn the user if they have to top up the account.

That being said, before "publishing" the bot, it would be nice to have an updated version of the flow diagram (f.e., in the README) so testers know what to expect.

**Comment by bee344** [comment]
I'm thinking of making the bot exit when outside of the renewal window, since when buying on the open market it's unlikely the core purchased will be the same, so it makes more sense to have it throw a warning, exit and then to be restarted once we know what's the new core ID.

**Comment by bee344** [comment]
Closed by #3
